name: push api action

on:
  push:
    branches:
      - master
    paths:
      - 'api/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.API_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.API_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Build
        run: |
          cd api/src
          zip get.zip get.js
          zip update.zip update.js
          zip delete.zip delete.js
      - name: Deploy
        if: steps.changes.outputs.src == 'true'
        env:
          S3_UPLOAD_BUCKET: ${{ secrets.S3_UPLOAD_BUCKET }}
        run: |
          aws s3 cp ./get.zip s3://$API_S3_UPLOAD_BUCKET/get.zip
          aws s3 cp ./update.zip s3://$API_S3_UPLOAD_BUCKET/update.zip
          aws s3 cp ./delete.zip s3://$API_S3_UPLOAD_BUCKET/delete.zip
